### PR TITLE
[DNM] Library Update

### PR DESCRIPTION
**Pull request by AffectedArc07**
Updates are good and theres a chance this will resolve the memory leaks, as well as hopefully resolving the spurious authentication failures. 

DNM for now since this needs testing and I am not able to at this moment in time.

### CODE REVIEW

**Review by Cyberboss — CHANGES_REQUESTED** [review]
Don't update the EFCore packages past 3.X.X. The 5.X.X versions are for .NET 5

**Comment by AffectedArc07** [comment]
And this is why its tagged as DNM

**Comment by AffectedArc07** [comment]
Tried this copy of libraries, and ran into these errors when processing
[IDB Errors.txt](https://github.com/tgstation/IconDiffBot/files/5006897/IDB.Errors.txt)

**Comment by AffectedArc07** [comment]
Someone more qualified can deal with this

**Pull request closed without merging**
